/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.Player;
import extractor.*;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;

import socket.Socket;
import socket.SaveQuotes;

/**
 *
 * @author kix
 */
public class QuotazioniUI extends javax.swing.JFrame {
    
    private ArrayList<ArrayList<Player>> listaPlayers = new ArrayList<>();
    private SaveQuotes saveQuotes;
   
    /**
     * Creates new form q
     */
    public QuotazioniUI() throws IOException {
        
        initComponents();
        this.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        this.saveQuotes = new SaveQuotes();
        this.listaPlayers = extractor.extract();
        //this.fillTable();
        
    }

    public void fillTable(){
        
        DefaultTableModel tm = (DefaultTableModel) jTable1.getModel();
        tm.setRowCount(0);
       
            
            for (List<Player> l : listaPlayers) {
                for (Player g : l) {

                    tm.addRow(new Object[]{g.getNome(), g.getSquadra(), g.getQuotazione(), g.getRuolo()});
                    
                }

            }
    }
    
    
    public void fillGoalKeeperTable(){
        
        DefaultTableModel tm = (DefaultTableModel) jTable1.getModel();
        tm.setRowCount(0);
        
         for (List<Player> l : this.listaPlayers) {
                for (Player g : l) {
                    if(g.getRuolo().equals("portiere")){
                        tm.addRow(new Object[]{g.getNome(), g.getSquadra(), g.getQuotazione(), g.getRuolo(),g.getBuyPrice(), g.getFantaTeam()});
                    }
                }

            }
    }
    
    public void fillDifenseTable(){
        
        DefaultTableModel tm = (DefaultTableModel) jTable1.getModel();
        tm.setRowCount(0);
        
         for (List<Player> l : this.listaPlayers) {
                for (Player g : l) {
                    if(g.getRuolo().equals("difensore")){
                        tm.addRow(new Object[]{g.getNome(), g.getSquadra(), g.getQuotazione(), g.getRuolo(),g.getBuyPrice(), g.getFantaTeam()});
                    }
                }

            }
    }
    
     public void fillMidfielderTable(){
        
        DefaultTableModel tm = (DefaultTableModel) jTable1.getModel();
        tm.setRowCount(0);
        
         for (List<Player> l : this.listaPlayers) {
                for (Player g : l) {
                    if(g.getRuolo().equals("centrocampista")){
                        tm.addRow(new Object[]{g.getNome(), g.getSquadra(), g.getQuotazione(), g.getRuolo(),g.getBuyPrice(), g.getFantaTeam()});
                    }
                }

            }
    } 
     
     public void fillAttackerTable(){
        
        DefaultTableModel tm = (DefaultTableModel) jTable1.getModel();
        tm.setRowCount(0);
        
         for (List<Player> l : this.listaPlayers) {
                for (Player g : l) {
                    if(g.getRuolo().equals("attaccante")){
                        tm.addRow(new Object[]{g.getNome(), g.getSquadra(), g.getQuotazione(), g.getRuolo(),g.getBuyPrice(), g.getFantaTeam()});
                    }
                }

            }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        buttonMod = new javax.swing.JButton();
        buttonSave = new javax.swing.JButton();
        jTextFieldQuot = new javax.swing.JTextField();
        buttonApply = new javax.swing.JButton();
        togglePortieri = new javax.swing.JToggleButton();
        toggleDifensori = new javax.swing.JToggleButton();
        toggleCentro = new javax.swing.JToggleButton();
        toggleAttaccanti = new javax.swing.JToggleButton();
        toggleAll = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldPrice = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Squadra", "Quotazione", "Ruolo", "Prezzo", "Squadra"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jTextField1.setEditable(false);

        buttonMod.setText("Modifica");
        buttonMod.setName(""); // NOI18N
        buttonMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonModActionPerformed(evt);
            }
        });

        buttonSave.setText("Salva");
        buttonSave.setEnabled(false);
        buttonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveActionPerformed(evt);
            }
        });

        buttonApply.setText("Applica");
        buttonApply.setEnabled(false);
        buttonApply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonApplyActionPerformed(evt);
            }
        });

        togglePortieri.setText("Portieri");
        togglePortieri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                togglePortieriActionPerformed(evt);
            }
        });

        toggleDifensori.setText("Difensori");
        toggleDifensori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleDifensoriActionPerformed(evt);
            }
        });

        toggleCentro.setText("Centrocampisti");
        toggleCentro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleCentroActionPerformed(evt);
            }
        });

        toggleAttaccanti.setText("Attaccanti");
        toggleAttaccanti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleAttaccantiActionPerformed(evt);
            }
        });

        toggleAll.setText("Tutti");
        toggleAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleAllActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Giocatore");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Q");

        jTextFieldPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPriceActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("P");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "acdc", "acybris", "astronzo", "dlc", "fanfulla", "fantaroma", "felix", "gpsundergland", "lph", "naj", "paris", "vts" }));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Squadra");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(togglePortieri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(toggleDifensori, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(toggleCentro, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                    .addComponent(toggleAttaccanti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(toggleAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonMod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldQuot)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonApply, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(togglePortieri)
                        .addGap(18, 18, 18)
                        .addComponent(toggleDifensori)
                        .addGap(18, 18, 18)
                        .addComponent(toggleCentro)
                        .addGap(18, 18, 18)
                        .addComponent(toggleAttaccanti)
                        .addGap(18, 18, 18)
                        .addComponent(toggleAll)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonMod)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldQuot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonApply)
                    .addComponent(buttonSave)
                    .addComponent(jTextFieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonModActionPerformed
        
        this.buttonApply.setEnabled(true);
        this.jTextField1.setText(this.jTable1.getValueAt( this.jTable1.getSelectedRow(), 0).toString());
        this.jTextFieldQuot.setText(this.jTable1.getValueAt( this.jTable1.getSelectedRow(), 2).toString());
        this.jTextFieldPrice.setText(this.jTable1.getValueAt(this.jTable1.getSelectedRow(), 4).toString());
        
        
    }//GEN-LAST:event_buttonModActionPerformed

    private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveActionPerformed
        
        this.saveQuotes.saveQuotes(listaPlayers);
        
      
        
    }//GEN-LAST:event_buttonSaveActionPerformed

    private void buttonApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonApplyActionPerformed
        
        DefaultTableModel tm = (DefaultTableModel) jTable1.getModel();

        
        this.saveQuotes.deleteQuotes();
        this.buttonSave.setEnabled(true);
        for(List<Player> l : this.listaPlayers){
            for(Player p : l){
                if(p.getNome().equals(this.jTextField1.getText())){
                    
                    p.setQuotazione(Double.parseDouble(this.jTextFieldQuot.getText()));
                    p.setBuyPrice(Integer.parseInt(this.jTextFieldPrice.getText()));
                    p.setFantaTeam(this.jComboBox1.getSelectedItem().toString());
                }
                    
            }
        }
        
        this.jTable1.setValueAt(Double.parseDouble(jTextFieldQuot.getText()), jTable1.getSelectedRow(), 2);
        this.jTable1.setValueAt(Integer.parseInt(jTextFieldPrice.getText()), jTable1.getSelectedRow(), 4);
        this.jTable1.setValueAt(this.jComboBox1.getSelectedItem().toString(), jTable1.getSelectedRow(), 5);
    }//GEN-LAST:event_buttonApplyActionPerformed

    private void togglePortieriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_togglePortieriActionPerformed
        
        this.toggleAll.setSelected(false);
        this.toggleAttaccanti.setSelected(false);
        this.toggleCentro.setSelected(false);
        this.toggleDifensori.setSelected(false);
        
        fillGoalKeeperTable();
        
       
    }//GEN-LAST:event_togglePortieriActionPerformed

    private void toggleAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleAllActionPerformed
        this.togglePortieri.setSelected(false);
        this.toggleAttaccanti.setSelected(false);
        this.toggleCentro.setSelected(false);
        this.toggleDifensori.setSelected(false);
        
        fillTable();
    }//GEN-LAST:event_toggleAllActionPerformed

    private void toggleDifensoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleDifensoriActionPerformed
        this.togglePortieri.setSelected(false);
        this.toggleAttaccanti.setSelected(false);
        this.toggleCentro.setSelected(false);
        this.toggleAll.setSelected(false);
        
        fillDifenseTable();
    }//GEN-LAST:event_toggleDifensoriActionPerformed

    private void toggleCentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleCentroActionPerformed
        this.togglePortieri.setSelected(false);
        this.toggleAttaccanti.setSelected(false);
        this.toggleDifensori.setSelected(false);
        this.toggleAll.setSelected(false);
        
        fillMidfielderTable();
    }//GEN-LAST:event_toggleCentroActionPerformed

    private void toggleAttaccantiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleAttaccantiActionPerformed
        this.togglePortieri.setSelected(false);
        this.toggleCentro.setSelected(false);
        this.toggleDifensori.setSelected(false);
        this.toggleAll.setSelected(false);
        
        fillAttackerTable();
    }//GEN-LAST:event_toggleAttaccantiActionPerformed

    private void jTextFieldPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPriceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuotazioniUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuotazioniUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuotazioniUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuotazioniUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new QuotazioniUI().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(QuotazioniUI.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        });
    }
    
    private PlayerExtractor extractor = new PlayerExtractor();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonApply;
    private javax.swing.JButton buttonMod;
    private javax.swing.JButton buttonSave;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldPrice;
    private javax.swing.JTextField jTextFieldQuot;
    private javax.swing.JToggleButton toggleAll;
    private javax.swing.JToggleButton toggleAttaccanti;
    private javax.swing.JToggleButton toggleCentro;
    private javax.swing.JToggleButton toggleDifensori;
    private javax.swing.JToggleButton togglePortieri;
    // End of variables declaration//GEN-END:variables
}
