/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import extractor.VoteExtractor;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.WindowConstants;
import model.Formation;
import model.Vote;
import socket.SaveFormations;


/**
 *
 * @author kix
 */
public class VotesUI extends javax.swing.JFrame {

    /**
     * Creates new form VotesUI
     */
    private VoteExtractor ve = new VoteExtractor();
    private Map<String, Vote> votesMap = new HashMap<String,Vote>();
    private Map<String, Formation> formationsMap = new HashMap<String,Formation>();
    private SaveFormations saveFormations;
    
    public VotesUI() throws IOException {
        initComponents();
        ve.extractVotes();
        votesMap = ve.getVotes();
        this.saveFormations = new SaveFormations(this);
        this.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        

    }
    
    public void formationLoaded(){
        
        ArrayList<String> teams = new ArrayList<String>(); 
        Set<String> teamSet = this.formationsMap.keySet();
        
        for (String s : teamSet){
            teams.add(s);
        }
        this.jTextFieldFormation1.setText(teams.get(0));
        this.jTextFieldFormation2.setText(teams.get(1));
        this.jTextFieldFormation3.setText(teams.get(2));
        this.jTextFieldFormation4.setText(teams.get(3));
        this.jTextFieldFormation5.setText(teams.get(4));
        this.jTextFieldFormation6.setText(teams.get(5));
        this.jTextFieldFormation7.setText(teams.get(6));
        this.jTextFieldFormation8.setText(teams.get(7));
        this.jTextFieldFormation9.setText(teams.get(8));
        this.jTextFieldFormation10.setText(teams.get(9));
        this.jTextFieldFormation11.setText(teams.get(10));
        this.jTextFieldFormation12.setText(teams.get(11));
    }

    public Map<String, Formation> getFormationsMap() {
        return formationsMap;
    }

    public void setFormationsMap(Map<String, Formation> formationsMap) {
        this.formationsMap = formationsMap;
    }

    

    public Map<String, Vote> getVotesMap() {
        return votesMap;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonLoadFormations = new javax.swing.JButton();
        jTextFieldFormation1 = new javax.swing.JTextField();
        jTextFieldFormation2 = new javax.swing.JTextField();
        jTextFieldFormation3 = new javax.swing.JTextField();
        jTextFieldFormation4 = new javax.swing.JTextField();
        jTextFieldFormation5 = new javax.swing.JTextField();
        jTextFieldFormation6 = new javax.swing.JTextField();
        jTextFieldFormation7 = new javax.swing.JTextField();
        jTextFieldFormation8 = new javax.swing.JTextField();
        jTextFieldFormation9 = new javax.swing.JTextField();
        jTextFieldFormation10 = new javax.swing.JTextField();
        jTextFieldFormation11 = new javax.swing.JTextField();
        jTextFieldFormation12 = new javax.swing.JTextField();
        jButtonDetail1 = new javax.swing.JButton();
        jButtonDetail2 = new javax.swing.JButton();
        jButtonDetail3 = new javax.swing.JButton();
        jButtonDetail4 = new javax.swing.JButton();
        jButtonDetail5 = new javax.swing.JButton();
        jButtonDetail6 = new javax.swing.JButton();
        jButtonDetail7 = new javax.swing.JButton();
        jButtonDetail8 = new javax.swing.JButton();
        jButtonDetail9 = new javax.swing.JButton();
        jButtonDetail10 = new javax.swing.JButton();
        jButtonDetail11 = new javax.swing.JButton();
        jButtonDetail12 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonLoadFormations.setText("Carica formazioni");
        jButtonLoadFormations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoadFormationsActionPerformed(evt);
            }
        });

        jTextFieldFormation1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFormation1ActionPerformed(evt);
            }
        });

        jTextFieldFormation2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFormation2ActionPerformed(evt);
            }
        });

        jTextFieldFormation3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFormation3ActionPerformed(evt);
            }
        });

        jTextFieldFormation4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFormation4ActionPerformed(evt);
            }
        });

        jTextFieldFormation5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFormation5ActionPerformed(evt);
            }
        });

        jTextFieldFormation6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFormation6ActionPerformed(evt);
            }
        });

        jTextFieldFormation7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFormation7ActionPerformed(evt);
            }
        });

        jTextFieldFormation8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFormation8ActionPerformed(evt);
            }
        });

        jTextFieldFormation9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFormation9ActionPerformed(evt);
            }
        });

        jTextFieldFormation10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFormation10ActionPerformed(evt);
            }
        });

        jTextFieldFormation11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFormation11ActionPerformed(evt);
            }
        });

        jTextFieldFormation12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFormation12ActionPerformed(evt);
            }
        });

        jButtonDetail1.setText("Dettagli");

        jButtonDetail2.setText("Dettagli");

        jButtonDetail3.setText("Dettagli");

        jButtonDetail4.setText("Dettagli");

        jButtonDetail5.setText("Dettagli");

        jButtonDetail6.setText("Dettagli");

        jButtonDetail7.setText("Dettagli");

        jButtonDetail8.setText("Dettagli");

        jButtonDetail9.setText("Dettagli");

        jButtonDetail10.setText("Dettagli");

        jButtonDetail11.setText("Dettagli");

        jButtonDetail12.setText("Dettagli");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jButtonLoadFormations)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 533, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldFormation6, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDetail6, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldFormation4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDetail5, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldFormation12, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDetail12, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldFormation11, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDetail10, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldFormation10, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDetail11, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldFormation9, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDetail7, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldFormation8, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDetail9, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldFormation7, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDetail8, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldFormation3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDetail3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldFormation2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDetail2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldFormation1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDetail1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldFormation5, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDetail4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(81, 81, 81))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jButtonLoadFormations, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jButtonDetail1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTextFieldFormation1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldFormation2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonDetail2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldFormation3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonDetail3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldFormation5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonDetail4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldFormation4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonDetail5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldFormation6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonDetail6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldFormation9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonDetail7))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldFormation7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonDetail8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldFormation8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonDetail9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldFormation11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonDetail10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldFormation10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonDetail11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldFormation12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonDetail12))))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLoadFormationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoadFormationsActionPerformed
        this.saveFormations.getFormationsByDB();
    }//GEN-LAST:event_jButtonLoadFormationsActionPerformed

    private void jTextFieldFormation1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFormation1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFormation1ActionPerformed

    private void jTextFieldFormation2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFormation2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFormation2ActionPerformed

    private void jTextFieldFormation3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFormation3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFormation3ActionPerformed

    private void jTextFieldFormation4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFormation4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFormation4ActionPerformed

    private void jTextFieldFormation5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFormation5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFormation5ActionPerformed

    private void jTextFieldFormation6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFormation6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFormation6ActionPerformed

    private void jTextFieldFormation7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFormation7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFormation7ActionPerformed

    private void jTextFieldFormation8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFormation8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFormation8ActionPerformed

    private void jTextFieldFormation9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFormation9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFormation9ActionPerformed

    private void jTextFieldFormation10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFormation10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFormation10ActionPerformed

    private void jTextFieldFormation11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFormation11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFormation11ActionPerformed

    private void jTextFieldFormation12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFormation12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFormation12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VotesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VotesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VotesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VotesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new VotesUI().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(VotesUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDetail1;
    private javax.swing.JButton jButtonDetail10;
    private javax.swing.JButton jButtonDetail11;
    private javax.swing.JButton jButtonDetail12;
    private javax.swing.JButton jButtonDetail2;
    private javax.swing.JButton jButtonDetail3;
    private javax.swing.JButton jButtonDetail4;
    private javax.swing.JButton jButtonDetail5;
    private javax.swing.JButton jButtonDetail6;
    private javax.swing.JButton jButtonDetail7;
    private javax.swing.JButton jButtonDetail8;
    private javax.swing.JButton jButtonDetail9;
    private javax.swing.JButton jButtonLoadFormations;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldFormation1;
    private javax.swing.JTextField jTextFieldFormation10;
    private javax.swing.JTextField jTextFieldFormation11;
    private javax.swing.JTextField jTextFieldFormation12;
    private javax.swing.JTextField jTextFieldFormation2;
    private javax.swing.JTextField jTextFieldFormation3;
    private javax.swing.JTextField jTextFieldFormation4;
    private javax.swing.JTextField jTextFieldFormation5;
    private javax.swing.JTextField jTextFieldFormation6;
    private javax.swing.JTextField jTextFieldFormation7;
    private javax.swing.JTextField jTextFieldFormation8;
    private javax.swing.JTextField jTextFieldFormation9;
    // End of variables declaration//GEN-END:variables
}
